sonar.projectKey=yassingdm_Groupe-5-Genie-Logiciel
sonar.organization=yassingdm
sonar.java.binaries=target/classes
sonar.projectBaseDir=grp5
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
